version: "3.7"

# Services
services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=ct_device_service_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_db_data:/var/lib/pgadmin

volumes:
  postgres_db_data: