apiVersion: v1
kind: ConfigMap
metadata:
  name: clozingtag-device-service-configmap
data:
  active-profile: "default"
  openapi-gateway-url: "http://localhost:8181/api/device" #  "https://live.clozingtag.com/api/device"
  base-url: "http://clozingtag-gateway-service-svc:8181" # https://live.clozingtag.com


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clozingtag-device-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clozingtag-device-service-deployment
  template:
    metadata:
      labels:
        app: clozingtag-device-service-deployment
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: -XX:TieredStopAtLevel=1 -noverify -Xms128m -Xmx512m -Xss4m -XX:ParallelGCThreads=1
                -XX:ConcGCThreads=1 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1
                -cp .
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: active-profile
                  name: clozingtag-device-service-configmap
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: clozingtag-device-service-configmap
                  key: base-url
            - name: DISCOVERY_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: clozingtag-discovery-service-configmap
                  key: discovery-server-url
            - name: AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: clozingtag-auth-service-configmap
                  key: auth-server-url
            - name: OPENAPI_GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: clozingtag-device-service-configmap
                  key: openapi-gateway-url
            #            - name: CONFIG_SERVER
            #              valueFrom:
            #                configMapKeyRef:
            #                  name: clozingtag-device-service-configmap
            #                  key: config-server-url
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: clozingtag-device-service-db-configmap
                  key: db-host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: clozingtag-device-service-db-configmap
                  key: db-port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: clozingtag-device-service-db-configmap
                  key: db-name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: clozingtag-device-service-db-secret
                  key: db-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: clozingtag-device-service-db-secret
                  key: db-pass
          image: ghcr.io/clozingtag/clozingtag-device-service:1e0cdf7  #to be updated by the workflow
          imagePullPolicy: IfNotPresent
          name: clozingtag-device-service
          ports:
            - containerPort: 8183
              protocol: TCP
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: clozingtag-device-service-svc
spec:
  selector:
    app: clozingtag-device-service-deployment
  ports:
    - protocol: "TCP"
      port: 8183
      targetPort: 8183
  type: ClusterIP